"""BUILDMAP.md -- where to look. Generated, never hand-edited.

    python tests/buildmap.py            writes BUILDMAP.md at the root
    python tests/buildmap.py --check    exit 1 if BUILDMAP.md is stale (CI)

The operator's ask, 2026-09-04: "the chainkit and modules are too much to be
grepped properly without some kind of build map or architecture oversight,
as in 'where to look' in the modules for certain functions." This is that
map, read off the code with `ast` so it cannot drift from it -- the same
instrument the landing gate and `windowed()` already use (DESIGN 14.10).

Three tables:

  MODULES     every chainkit/*.py: its first docstring line, its size, and
              every top-level class and function with its line range.
  GUARDS      every `# THE ... (sitting N)` / `SITTING N` / `session N`
              marker inside a definition, so a guard can be found by the
              failure that earned it.
  STROKES     every test_* function in tests/, the chainkit names it
              touches, and its line range -- the "where is this proved"
              half of where-to-look.

Facts read, never generated: nothing here is written from memory of the
code. A `--check` in CI proves the committed map is the code's map.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "BUILDMAP.md"
PKG = ROOT / "chainkit"
TESTS = ROOT / "tests"

_MARK = re.compile(
    r"(?i)\b(?:sitting|session)\s+(\d+[a-z]?)\b|\b(20\d\d-\d\d-\d\d)\b")


def _first_doc_line(node) -> str:
    doc = ast.get_docstring(node) or ""
    return doc.strip().splitlines()[0].strip() if doc.strip() else ""


def _defs(tree):
    out = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            out.append(("def", node.name, node.lineno,
                        getattr(node, "end_lineno", node.lineno), _first_doc_line(node)))
        elif isinstance(node, ast.ClassDef):
            out.append(("class", node.name, node.lineno,
                        getattr(node, "end_lineno", node.lineno), _first_doc_line(node)))
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    out.append(("  def", f"{node.name}.{child.name}", child.lineno,
                                getattr(child, "end_lineno", child.lineno),
                                _first_doc_line(child)))
    return out


def _guards(src: str, tree):
    """Markers of the failure that earned a piece of code, by definition."""
    lines = src.splitlines()
    spans = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            spans.append((node.lineno, getattr(node, "end_lineno", node.lineno), node.name))
    out = []
    for i, line in enumerate(lines, 1):
        s = line.strip()
        if not (s.startswith("#") or s.startswith('"""') or "SITTING" in s.upper()):
            continue
        m = _MARK.search(s)
        if not m:
            continue
        # the innermost definition holding this line
        owner = ""
        best = 10 ** 9
        for lo, hi, name in spans:
            if lo <= i <= hi and (hi - lo) < best:
                best, owner = hi - lo, name
        text = s.lstrip("# ").strip()[:90]
        out.append((i, owner or "(module)", text))
    return out


def _stroke_refs(node, names: set[str]) -> list[str]:
    refs = set()
    for sub in ast.walk(node):
        if isinstance(sub, ast.Name) and sub.id in names:
            refs.add(sub.id)
        elif isinstance(sub, ast.Attribute):
            root = sub
            while isinstance(root, ast.Attribute):
                root = root.value
            if isinstance(root, ast.Name) and root.id in names:
                refs.add(f"{root.id}.{sub.attr}")
    return sorted(refs)[:12]


def render() -> str:
    out = ["# BUILDMAP — where to look", "",
           "GENERATED by `python tests/buildmap.py` from the code with `ast`. Never",
           "hand-edited; `python tests/buildmap.py --check` in CI refuses a stale copy.",
           "Line numbers are as of the generating commit -- regenerate after a change.",
           "", "Reading order for a stranger: BUILDPATH.md (the layers and why) ->",
           "this file (where each thing is) -> REFUSALS.md (what each guard refuses)",
           "-> the module's own docstring.", ""]

    modules = sorted(p for p in PKG.glob("*.py"))
    out += ["## MODULES", ""]
    total = 0
    for p in modules:
        src = p.read_text(encoding="utf-8", errors="replace")
        try:
            tree = ast.parse(src)
        except SyntaxError as exc:
            out += [f"### chainkit/{p.name} — DOES NOT PARSE: {exc}", ""]
            continue
        n = len(src.splitlines())
        total += n
        out += [f"### chainkit/{p.name} — {n} lines", "",
                f"*{_first_doc_line(tree) or '(no docstring)'}*", ""]
        defs = _defs(tree)
        if defs:
            out.append("| kind | name | lines | says |")
            out.append("|---|---|---|---|")
            for kind, name, lo, hi, doc in defs:
                out.append(f"| {kind.strip()} | `{name}` | {lo}-{hi} | {doc[:80]} |")
            out.append("")
    out += [f"chainkit/: {len(modules)} files, {total} lines.", ""]

    out += ["## GUARDS — by the failure that earned them", "",
            "Every comment or docstring line inside `chainkit/` that names a sitting,",
            "a session or a date, with the definition it sits in. Grep the sitting",
            "number in SEAT_LOG.md for the toll; the transcript is named there.", ""]
    for p in modules:
        src = p.read_text(encoding="utf-8", errors="replace")
        try:
            tree = ast.parse(src)
        except SyntaxError:
            continue
        gs = _guards(src, tree)
        if not gs:
            continue
        out += [f"### chainkit/{p.name}", "", "| line | in | marker |", "|---|---|---|"]
        for i, owner, text in gs:
            out.append(f"| {i} | `{owner}` | {text} |")
        out.append("")

    out += ["## STROKES — where each thing is proved", "",
            "Every `test_*` function in tests/, the chainkit names it touches, and",
            "its line range. The suites are the memory (HANDOFF: test discipline).", ""]
    pkg_names = {p.stem for p in modules} | {"chainkit"}
    for tp in sorted(TESTS.glob("*.py")):
        src = tp.read_text(encoding="utf-8", errors="replace")
        try:
            tree = ast.parse(src)
        except SyntaxError:
            continue
        # names imported from chainkit, so references can be attributed
        imported = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("chainkit"):
                for a in node.names:
                    imported.add(a.asname or a.name)
            elif isinstance(node, ast.Import):
                for a in node.names:
                    if a.name.startswith("chainkit"):
                        imported.add((a.asname or a.name).split(".")[0])
        tests = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name.startswith("test_")]
        if not tests:
            continue
        out += [f"### tests/{tp.name} — {len(tests)} test functions", "",
                "| test | lines | touches |", "|---|---|---|"]
        for t in tests:
            refs = _stroke_refs(t, imported | pkg_names)
            out.append(f"| `{t.name}` | {t.lineno}-{getattr(t, 'end_lineno', t.lineno)} "
                       f"| {', '.join(f'`{r}`' for r in refs) or '—'} |")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
        if current != text:
            print("BUILDMAP.md is STALE: regenerate with `python tests/buildmap.py`")
            return 1
        print("BUILDMAP.md matches the code.")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\r\n")
    print(f"wrote {OUT.name}: {len(text.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
